import streamlit as st
import pandas as pd

st.header("Fundamental Analysis report")
st.markdown("Generated by FinGPT")

for message in st.session_state.messages:
    if message.name == "FinGPT":
        st.write(f"Content: {message.content}")
        st.write(f"Name: {message.name}")
        st.markdown("---")

balance_sheet = pd.read_csv('balance_sheet.csv')
cash_flow = pd.read_csv('cash_flow.csv')
income_stmt = pd.read_csv('income_stmt.csv')

st.subheader('Balance sheet')
st.divider()
st.dataframe(balance_sheet)

st.subheader('Cash Flow')
st.divider()
st.dataframe(cash_flow)

st.subheader('Income statement')
st.divider()
st.dataframe(income_stmt)
